// Code generated by command: go run gen.go -out matrix_avx/add.s -stubs matrix_avx/stub.go -pkg matrix_avx. DO NOT EDIT.

package matrix_avx

// VecAddAVX suma los elementos de a y b usando registros YMM de 256 bits.
func VecAddAVX(a []float32, b []float32, res []float32)
